#ifndef LOGGING_CATEGORIES_H
#define LOGGING_CATEGORIES_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(logCore)
Q_DECLARE_LOGGING_CATEGORY(logNet)
Q_DECLARE_LOGGING_CATEGORY(logDb)

#endif // LOGGING_CATEGORIES_H
